# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 08:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20160317_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallimg_url',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 17, 8, 11, 42, 873971)),
        ),
    ]
