# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 09:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20160317_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 17, 9, 59, 19, 756156)),
        ),
        migrations.AlterField(
            model_name='user',
            name='wallimg_url',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
