# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 10:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20160317_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 17, 10, 3, 54, 174026)),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_url',
            field=models.CharField(default=b'/static/images/user.png', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='wallimg_url',
            field=models.CharField(default=b'/static/images/banner1.png', max_length=250, null=True),
        ),
    ]
